export const CLOUDINARY_CLOUD_NAME = "dazeo3dch";
export const CLOUDINARY_UPLOAD_PRESET = "images";
export const CLOUDINARY_API_KEY = "REMOVED_CLOUDINARY_KEY";
export const CLOUDINARY_API_SECRET = "REMOVED_CLOUDINARY_SECRET";
