export const EN_UNIT_MAP = {
  g: "g",
  gram: "g",
  grams: "g",
  kg: "kg",
  ml: "ml",
  l: "l",
  tsp: "tsp",
  teaspoon: "tsp",
  teaspoons: "tsp",
  tbsp: "tbsp",
  tablespoon: "tbsp",
  tablespoons: "tbsp",
  cup: "cup",
  cups: "cup",
  pinch: "pinch",
  clove: "clove",
  cloves: "clove",
  piece: "piece",
  pieces: "piece",
  "": "each",
};
