/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/qrPayment`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/menu` | `/menu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/menu/[id]` | `/menu/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(user)'}/orders/[id]` | `/orders/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/qrPayment`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(user)'}/menu` | `/menu`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(user)'}/orders` | `/orders`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(user)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(user)'}/menu/[id]` | `/menu/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(user)'}/orders/[id]` | `/orders/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/cart${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/qrPayment${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(user)'}/menu${`?${string}` | `#${string}` | ''}` | `/menu${`?${string}` | `#${string}` | ''}` | `${'/(user)'}/orders${`?${string}` | `#${string}` | ''}` | `/orders${`?${string}` | `#${string}` | ''}` | `${'/(user)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/qrPayment`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/menu` | `/menu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `${'/(user)'}/menu/${Router.SingleRoutePart<T>}` | `/menu/${Router.SingleRoutePart<T>}` | `${'/(user)'}/orders/${Router.SingleRoutePart<T>}` | `/orders/${Router.SingleRoutePart<T>}` | { pathname: `${'/(user)'}/menu/[id]` | `/menu/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(user)'}/orders/[id]` | `/orders/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
